Allow for connect and subscribe packets larger than 128 bytes
SodaqMoja/Sodaq_MQTT pull request #4
Opened 2021-08-24 14:37 UTC by floriaanpost

To connect to Azure IoT hub I needed a subscribe packet larger than 128 bytes as the username and password fields are quite large. 

It took me some time to figure out why it did not work, but in the end I discovered that the current implementation assumes that the connect (and subscribe packets too) are never larger than 128 bytes. I fixed it using the pseudocode found in the [MQTT docs](https://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718023) 

Later on I discovered that there was already an implementation for the publish packet, I changed that too.

2021-08-29 18:28 UTC, SodaqMoja commented
Thanks Florian for reporting this.

I like to request a few changes before merging.

2021-08-29 19:33 UTC, SodaqMoja requested changes

2021-08-29 19:33 UTC, SodaqMoja commented on src/Sodaq_MQTT.cpp
> +size_t MQTT::writeVariableLengthInt(size_t length, uint8_t **ptr)
There is already a function that reads the "remaining length". Let's rename this function to `writeRemainingLength`.

2021-08-29 19:33 UTC, SodaqMoja commented on src/Sodaq_MQTT.cpp
> +size_t MQTT::writeVariableLengthInt(size_t length, uint8_t **ptr)
Since this is C++ I have a preference for a "reference" instead of a double pointer.

Something like:
```
size_t MQTT::writeRemainingLength(size_t length, uint8_t * & ptr)
{
...
      *ptr++ = encodedByte;
```

2021-08-29 19:33 UTC, SodaqMoja commented on src/Sodaq_MQTT.cpp
> +    {
The coding style of this library has the curly bracket at the end of `for`, `while`, `do` statements. Please correct that.

2021-08-29 19:33 UTC, SodaqMoja commented on src/Sodaq_MQTT.cpp
>      debugDump(pckt, pckt_len + 2);
You forgot to update this `pckt_len + 2`.

In fact, there is one more occurance of `pckt_len + 2` in this function. Which tells me that this function needs a bit more refactoring. I should have added more comments when I wrote this.

2021-08-29 19:33 UTC, SodaqMoja commented on src/Sodaq_MQTT.cpp
>      debugDump(pckt, 1 + remaining_bytes + remaining);
You forgot to update `1 + remaining_bytes + remaining`

2021-08-29 19:37 UTC, SodaqMoja commented
@floriaanpost How familiar are you with Git? I'm asking because it is more common to first create a branch in which you make your changes. With that branch you make a Pull Request. If it is accepted and merged the branch can easily be deleted. That way the `master` branch will not get conflicts with the original `master`.

2021-08-30 20:46 UTC, floriaanpost commented
@SodaqMoja Thank for your comments! It is actually the first time I contribute to an open source project, but it makes a lot of sense to create a new branch first before creating a merge request, I would do the same in my work ;). Is it for now OK to keep it the way it is? I fixed all the above comments.

2021-08-30 21:03 UTC, SodaqMoja approved these changes

2021-08-30 21:04 UTC, SodaqMoja commented
Looks good now. Can you squash?

2021-08-31 09:39 UTC, floriaanpost commented
Done!

2021-08-31 19:34 UTC, merged

2021-08-31 19:34 UTC, SodaqMoja commented
Thanks Floriaan